// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.loopiadns;

import com.pulumi.core.internal.Codegen;
import java.lang.String;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("loopia-dns");
    public String endpoint() {
        return Codegen.stringProp("endpoint").config(config).require();
    }
    public String password() {
        return Codegen.stringProp("password").config(config).require();
    }
    public String username() {
        return Codegen.stringProp("username").config(config).require();
    }
}
