// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"example.com/pulumi-loopia-dns/sdk/go/loopia-dns/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

func GetEndpoint(ctx *pulumi.Context) string {
	return config.Get(ctx, "loopia-dns:endpoint")
}
func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "loopia-dns:password")
}
func GetUsername(ctx *pulumi.Context) string {
	return config.Get(ctx, "loopia-dns:username")
}
