# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_loopia_dns.config as __config
    config = __config
    import pulumi_loopia_dns.pkg as __pkg
    pkg = __pkg
else:
    config = _utilities.lazy_import('pulumi_loopia_dns.config')
    pkg = _utilities.lazy_import('pulumi_loopia_dns.pkg')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "loopia-dns",
  "mod": "pkg",
  "fqn": "pulumi_loopia_dns.pkg",
  "classes": {
   "loopia-dns:pkg:DnsRecord": "DnsRecord"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "loopia-dns",
  "token": "pulumi:providers:loopia-dns",
  "fqn": "pulumi_loopia_dns",
  "class": "Provider"
 }
]
"""
)
